### ISSUE TITLE
pull or fork

### ISSUE THREAD

**Issue by emielvanberlo** [probonopd/OpenPhone#4]
Hi, 

Just clicked on Fork, but was wondering if a Pull request might be better.

I want to try to use this project on a new Rasberry Pi Compute Module 4 with IO Board to restore phone functions on an old Dutch Payphone. (Landis & Gyr manufactured early-mid 199x) These phones were all over the world in different configurations.
(https://gathering.tweakers.net/forum/list_messages/1812719 is in dutch but with google translate you get a pretty good understanding what me and a couple of others have tried)

First we tried if we could let the phone work as is, but the phone depends on a central management system which (of course) is out of service. My plan was to create a new voip phone and emulate the way it acted when it was in service.

Regards,
Emiel

**Comment by probonopd** [comment]
Hello @emielvanberlo. Thanks for your interest in OpenPhone.
Fork is correct, you now have your own copy of this repository in which you can make your changes to make the code work with your hardware.

Good luck with your project!
Let me know if questions arise.
