### ISSUE TITLE
pjsip python library

### ISSUE THREAD

**Issue by emielvanberlo** [probonopd/OpenPhone#5]
Hi, I was browsing a bit and I read that the PJSUA python module has been superseded by a new PJSUA2 module.
https://www.pjsip.org/docs/book-latest/html/intro_pjsua2.html
Any idea how much work it would be to upgrade this in this project?

**Comment by probonopd** [comment]
Hi @emielvanberlo, I have no experience with PJSUA2 so I cannot say. But you can look through the OpenPhone source code to see in which places we are using PJSUA to get an idea of how much would need to be touched. Have fun!
